### ISSUE TITLE
Artifacts page is empty

### ISSUE THREAD

**Issue by joaco-espinosa** [ngeor/kafka-windows-service-wrapper#2]
Hello,

The [artifacts page](https://ci.appveyor.com/project/ngeor/kafka-windows-service-wrapper/build/artifacts) doesn't show any results. There's a message on top that reads:
> _Artifacts older than 6 months will be deleted after June 17th, 2018. For more details see Artifacts retention policy._

Could you please upload your binaries to a different repository? Thanks.

**Comment by ngeor** [comment]
Hi Joaco,

thank you for bringing the issue to my attention. I have made some modifications so that the necessary files are automatically published as a release in this GitHub repository. I have updated the README file so everything should work again.

Best regards,
Nikolaos
